pipeline:

  value-for-success:
    image: quay.io/ukhomeofficedigital/snowtify:latest
    title: '[ "${DRONE_BUILD_STATUS}" = "success" ] && echo "all good" || echo "something wicked"'
    description: '$$( [ "${DRONE_BUILD_STATUS}" = "success" ] && echo "all good" || echo "something wicked" )'
    testing: '`[ "${DRONE_BUILD_STATUS}" = "success" ] && echo "all good" || echo "something wicked"`'
