pipeline:

  deploy:
    image: quay.io/ukhomeofficedigital/snowtify:0.0.1-d78d7a0a9e
    commands:
      - echo "droning on!"
      - pwd
      - ls -al
      - cd /app
      - ls -al
      - echo "$PWD"
      - echo "$OLDPWD"
      - ls -al /tmp
      - ls -al /drone
      - ls -al /drone/*
      - ls -al /drone/src/*
      - ls -al /drone/src/github.com/*
      - echo "$HOME"
      - echo test > test.log
      - cd
      - pwd
    when:
      event: [ push ]
