pipeline:

  deploy:
    image: docker:1.11
    commands:
      - set +e
      - echo "some text" > txt
      - cat $!
      - XIT=$?
      - printf "xit $${XIT}\n" > rslt
      - cat rslt
      - echo "some text" > txt2
      - cat $$!
      - XIT=$$?
      - printf "xit $${XIT}\n" > rslt
      - cat rslt
    when:
      event: push
