pipeline:

  deploy:
    commands:
      - echo "droning on!"
      - echo "drone build $${DRONE_BUILD_NUMBER}"
      - echo "event $${event}"
      - echo "env $${env}"
    when:
      event: [deployment, push]
      branch: master

matrix:
  include:
    - event: push
      env: dev
    - event: deployment
      env: uat
    - event: deployment
      env: preprod
    - event: deployment
      env: prod