pipeline:

  cause-a-fail:
    image: ukhomeoffice/drone-docker
    commands:
      - exit 2
    when:
      event: push

  check-env-vars:
    image: ukhomeoffice/drone-docker
    commands:
      - set
    when:
      status: failure
